name: release

on:
  workflow_dispatch:
    inputs:
      run_tests:
        description: Run test step
        required: false
        default: false
        type: boolean
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - uses: actions/checkout@v6
    - name: get-version
      id: get_version
      run: |
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
          echo "VERSION=manual-${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
        fi
    - name: opencv4-source
      env:
        opencv-version: 4.13.0
      run: |
        wget -q https://github.com/opencv/opencv/archive/${{ env.opencv-version }}.zip -O opencv-${{ env.opencv-version }}.zip
        unzip -q opencv-${{ env.opencv-version }}.zip
        rm opencv-${{ env.opencv-version }}.zip
        cd opencv-${{ env.opencv-version }}
        truncate -s 0 cmake/OpenCVFindLibsGrfmt.cmake
        rm -rf modules/gapi

        truncate -s 0 cmake/platforms/OpenCV-Linux.cmake

        rm modules/core/src/cuda_*
        rm modules/core/src/direct*
        rm modules/core/src/gl_*
        rm modules/core/src/intel_gpu_*
        rm modules/core/src/ocl*
        rm modules/core/src/opengl.cpp
        rm modules/core/src/ovx.cpp
        rm modules/core/src/umatrix.hpp
        rm modules/core/src/va_intel.cpp
        rm modules/core/src/va_wrapper.impl.hpp

        rm modules/core/include/opencv2/core/cuda*.hpp
        rm modules/core/include/opencv2/core/directx.hpp
        rm modules/core/include/opencv2/core/ocl*.hpp
        rm modules/core/include/opencv2/core/opengl.hpp
        rm modules/core/include/opencv2/core/ovx.hpp
        rm modules/core/include/opencv2/core/private.cuda.hpp
        rm modules/core/include/opencv2/core/va_*.hpp
        rm -rf modules/core/include/opencv2/core/cuda
        rm -rf modules/core/include/opencv2/core/opencl
        rm -rf modules/core/include/opencv2/core/openvx

        rm modules/photo/src/denoising.cuda.cpp
        rm modules/photo/include/opencv2/photo/cuda.hpp

        find modules -type d | xargs -i rm -rf {}/src/cuda
        find modules -type d | xargs -i rm -rf {}/src/opencl
        find modules -type d | xargs -i rm -rf {}/perf/cuda
        find modules -type d | xargs -i rm -rf {}/perf/opencl
        find modules -type f | xargs -i sed -i '/opencl_kernels/d' {}
        find modules -type f | xargs -i sed -i '/cuda.hpp/d' {}
        find modules -type f | xargs -i sed -i '/opengl.hpp/d' {}
        find modules -type f | xargs -i sed -i '/ocl_defs.hpp/d' {}
        find modules -type f | xargs -i sed -i '/ocl.hpp/d' {}
        find modules -type f | xargs -i sed -i '/ovx_defs.hpp/d' {}
        find modules -type f | xargs -i sed -i '/ovx.hpp/d' {}
        find modules -type f | xargs -i sed -i '/va_intel.hpp/d' {}

        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-no-gpu.patch
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-no-rtti.patch
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-no-zlib.patch
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-link-openmp.patch
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-fix-windows-arm-arch.patch
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-minimal-install.patch
        cp ../patches/draw_text.h ../patches/mono_font_data.h modules/imgproc/src/
        cp ../patches/fontface.html ./
        patch -p1 -i ../patches/opencv-${{ env.opencv-version }}-drawing-mono-font.patch
        rm -rf modules/highgui
        cp -r ../highgui modules/
        rm -rf 3rdparty
        rm -rf apps data doc samples platforms
        rm -rf modules/java
        rm -rf modules/js
        rm -rf modules/python
        rm -rf modules/ts
        rm -rf modules/dnn
        sed -e 's/__VERSION__/${{ env.opencv-version }}/g' ../patches/Info.plist > ./Info.plist
        cp ../opencv4_cmake_options.txt ./options.txt
        cp -r ../toolchains .
        cd ..
        mv opencv-${{ env.opencv-version }} opencv-mobile-${{ env.opencv-version }}
        zip -9 -r opencv-mobile-${{ env.opencv-version }}.zip opencv-mobile-${{ env.opencv-version }}
    - name: upload-opencv4-source
      uses: actions/upload-artifact@v7
      with:
        name: opencv-mobile-4.13.0-source
        path: opencv-mobile-4.13.0.zip

  milkv-duo-sdk-v2:
    needs: [setup]
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    env:
      SOURCE_DIR: opencv-mobile-4.13.0
      PACKAGE_NAME: opencv-mobile-4.13.0-milkv-duo-sdk-v2
      RISCV_TOOLCHAIN_DIR: Xuantie-900-gcc-linux-5.10.4-musl64-x86_64-V2.8.1
      COMMON_CMAKE_OPTIONS: |
        -DCMAKE_TOOLCHAIN_FILE=../../toolchains/riscv64-unknown-linux-musl.toolchain.cmake \
        -DCMAKE_C_FLAGS="-fno-rtti -fno-exceptions" \
        -DCMAKE_CXX_FLAGS="-fno-rtti -fno-exceptions" \
        -DCMAKE_INSTALL_PREFIX=install \
        -DCMAKE_BUILD_TYPE=Release \
    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v8
      with:
        name: opencv-mobile-4.13.0-source
    - name: setup-toolchain
      run: |
        apt-get update
        apt-get install -y unzip zip patch cmake wget xz-utils
        wget -q https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource//1705396382457/Xuantie-900-gcc-linux-5.10.4-musl64-x86_64-V2.8.1-20240115.tar.gz
        tar -xf Xuantie-900-gcc-linux-5.10.4-musl64-x86_64-V2.8.1-20240115.tar.gz
        wget -q https://sophon-file.sophon.cn/sophon-prod-s3/drive/23/03/07/16/host-tools.tar.gz
        tar -xf host-tools.tar.gz
    - name: setup-opencv-source
      run: unzip -q opencv-mobile-4.13.0.zip
    - name: build
      run: |
        cd ${{ env.SOURCE_DIR }}
        patch -p1 -i ../patches/opencv-4.13.0-no-atomic.patch
        mkdir build && cd build
        export RISCV_ROOT_PATH=$GITHUB_WORKSPACE/${{ env.RISCV_TOOLCHAIN_DIR }}
        cmake ${{ env.COMMON_CMAKE_OPTIONS }} \
            `cat ../options.txt` -DBUILD_opencv_world=OFF -DOPENCV_DISABLE_FILESYSTEM_SUPPORT=ON \
            -DWITH_OPENMP=OFF -DOPENCV_DISABLE_THREAD_SUPPORT=ON \
            -DWITH_CVI=ON -DWITH_DUO_SDK_V2=ON -DWITH_HAL_RVV=OFF \
            -DOPENCV_EXTRA_FLAGS="-D__riscv_vector_071 -mrvv-vector-bits=128" ..
        cmake --build . -j $(nproc)
        cmake --build . --target install
    - name: package
      run: |
        mkdir ${{ env.PACKAGE_NAME }}
        cp -rf ${{ env.SOURCE_DIR }}/build/install/* ${{ env.PACKAGE_NAME }}/
        zip -9 -r ${{ env.PACKAGE_NAME }}.zip ${{ env.PACKAGE_NAME }}
    - name: test
      if: startsWith(github.ref, 'refs/tags/') || inputs.run_tests
      run: |
        cd test
        mkdir build && cd build
        export RISCV_ROOT_PATH=$GITHUB_WORKSPACE/host-tools/gcc/riscv64-linux-musl-x86_64
        cmake ${{ env.COMMON_CMAKE_OPTIONS }} -DOpenCV_DIR=$GITHUB_WORKSPACE/${{ env.PACKAGE_NAME }}/lib/cmake/opencv4 ..
        cmake --build . -j $(nproc)
    - name: upload-zip
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.PACKAGE_NAME }}.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: [setup, milkv-duo-sdk-v2]
    runs-on: ubuntu-latest
    steps:
    - name: download
      uses: actions/download-artifact@v8
      with:
        path: artifacts
    - name: create-release
      uses: softprops/action-gh-release@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ needs.setup.outputs.VERSION }}
        name: Release ${{ needs.setup.outputs.VERSION }}
        files: artifacts/*/*.zip
